### ISSUE TITLE
все по инструкции установил , запустил получил ошибку 

### ISSUE THREAD

**Issue by skoorpion963** [Nikita-Filonov/sample_api_testing#1]
(venv) taurus@taurus-pc:~/news_projects/APITests/sample_api_testing$ python -m pytest --alluredir=./allure-results
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pytest/__main__.py", line 5, in <module>
    raise SystemExit(pytest.console_main())
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 190, in console_main
    code = main()
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 148, in main
    config = _prepareconfig(args, plugins)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 329, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 130, in _multicall
    teardown[0].send(outcome)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/helpconfig.py", line 103, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1058, in pytest_cmdline_parse
    self.parse(args)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1346, in parse
    self._preparse(args, addopts=addopts)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1248, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 152, in _multicall
    return outcome.get_result()
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pluggy/_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 1125, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 560, in _set_initial_conftests
    self._try_load_conftest(current, namespace.importmode, rootpath)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 574, in _try_load_conftest
    self._getconftestmodules(anchor, importmode, rootpath)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 603, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode, rootpath)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 651, in _importconftest
    self.consider_conftest(mod)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 732, in consider_conftest
    self.register(conftestmodule, name=conftestmodule.__file__)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 496, in register
    self.consider_module(plugin)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 740, in consider_module
    self._import_plugin_specs(getattr(mod, "pytest_plugins", []))
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 747, in _import_plugin_specs
    self.import_plugin(import_spec)
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/config/__init__.py", line 774, in import_plugin
    __import__(importspec)
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
    exec(co, module.__dict__)
  File "/home/taurus/news_projects/APITests/sample_api_testing/utils/fixtures/questions.py", line 4, in <module>
    from models.authentication import Authentication
  File "/home/taurus/news_projects/APITests/sample_api_testing/models/authentication.py", line 3, in <module>
    from settings import base_settings
  File "/home/taurus/news_projects/APITests/sample_api_testing/settings.py", line 24, in <module>
    base_settings = Settings()
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pydantic_settings/main.py", line 71, in __init__
    super().__init__(
  File "/home/taurus/news_projects/APITests/sample_api_testing/venv/lib/python3.10/site-packages/pydantic/main.py", line 164, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
base_url
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.4/v/missing

**Comment by skoorpion963** [comment]
прикольно когда код из гайда не запускается )
у меня какие то ошибки с импортом , возможно дело в версии python, у вас какая версия ?

**Comment by Nikita-Filonov** [comment]
Этот репозиторий прилагается к статье https://habr.com/ru/articles/709380/

Ошибка выше вызвана тем, что в рутовой директории проекта `/home/taurus/news_projects/APITests/sample_api_testing`, отсутствует файл `.env`. Про это четко написано в статье:

> Мы будем читать настройки из .env файла.

> .env
> ```
> BASE_URL="https://api.sampleapis.com" # API endpoint
> TEST_USER.EMAIL="some@gmail.com" # Some random user just for example
> TEST_USER.PASSWORD="some" # Some random password just for example
> ```

И никакие импорты, версии и прочее тут ни при чем) Советую внимательно прочитать статью, тогда большинство вопросов/проблем решится)

**Comment by skoorpion963** [comment]
версия питона какая ? укажите тогда в инструкцию по установке необходимость внесения изменений
